module Data.Embedding where

-- !!! This Haskell module has been autogenerated by agda2hs.
-- !!! Do NOT change; change the original .agda file instead.

data Embedding a b = Embedding{to :: a -> b, from :: b -> a}

