module Language.FineTypes where

{-# FOREIGN AGDA2HS
-- !!! This Haskell module has been autogenerated by agda2hs.
-- !!! Do NOT change; change the original .agda file instead.
#-}

import Data.Embedding
import Language.FineTypes.Typ
import Language.FineTypes.Value.Def
import Language.FineTypes.Embedding
-- import Language.FineTypes.Value.Typcheck
