agents:
  queue: "cardano-wallet"

env:
  LC_ALL: "C.UTF-8"
  NIX_PATH: "channel:nixos-21.11"

  # Per-host variables - shared across containers on host
  macos: "x86_64-darwin"
  linux: "x86_64-linux"
  nix: "nix develop --accept-flake-config"

steps:

  - label: 'Check nix develop (linux)'
    key: linux-nix
    commands: |
      ${nix} --command bash -c "echo +++ nix develop"
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Check format'
    depends_on: linux-nix
    command: |
      ${nix} --command bash -c "echo +++ format; just format"
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Check lint'
    depends_on: linux-nix
    command: |
      ${nix} --command bash -c "echo +++ lint; just lint"
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"

  - label: 'Check Haskell Language Server (HLS)'
    depends_on: linux-nix
    command: |
      ${nix} --command bash -c "haskell-language-server lib/fine-types/src/Language/FineTypes.hs"
    agents:
      system: ${linux}
    env:
      TMPDIR: "/cache"
